#!/usr/bin/env sh

# Bootstrap new configuration.
cd
rm -rf dotfiles/ .config/nvim/ .tmux.conf .vim/
git clone --quiet https://github.com/senavis/mydots.git
mkdir .config/nvim/ .vim/
ln -s ~/dotfiles/init.vim ~/.config/nvim/init.vim
ln -s ~/dotfiles/vimrc.symlink ~/.vimrc
ln -s ~/dotfiles/tmux.conf ~/.tmux.conf

# Configure Git.
dotfiles/git-config

echo 'Starting Vim to install plugins...'
#nvim
vim
