#!/usr/bin/env sh

# Bootstrap new configuration.
cd
rm -rf mydots/ .config/nvim/ .tmux.conf .vim/
git clone --quiet https://github.com/senavis/mydots.git
mkdir .config/nvim/ .vim/
ln -s ~/mydots/init.vim ~/.config/nvim/init.vim
ln -s ~/mydots/vimrc.symlink ~/.vimrc
ln -s ~/mydots/tmux.conf ~/.tmux.conf

# Configure Git.
mydots/git-config

echo 'Starting Vim to install plugins...'
#nvim
vim
